swagger: '2.0'
info:
  title: Dana Backend REST API
  version: "0.1"
consumes:
  - application/json
produces:
  - application/json
paths:
  /greeting:
    post:
      tags: [Greeting]
      operationId: app.post_greeting
      summary: Returns a custom greeting.
      responses:
        200:
          description: Return greeting
          schema:
            type: object
          examples:
            application/json:
                greeting: "Hello John"
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              name:
                type: string
                example: "John"
            required:
              - name