version: "2.3"
services:
  app:
    build: .
    volumes: 
      - .:/code
      - ./db_info:/db_info
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: kartoza/postgis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASS: test
      ALLOW_IP_RANGE: 0.0.0.0/0
      PGUSER: postgres
      PGPASSWORD: test
      PGHOST: "localhost"