version: "2"
services:
  app:
    build: .
    volumes: 
      - .:/code
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: kartoza/postgis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASS: test
      ALLOW_IP_RANGE: 0.0.0.0/0