swagger: '2.0'
info:
  title: Dana Backend REST API
  version: "0.1"
consumes:
  - application/json
produces:
  - application/json
paths:
  /greeting:
    get:
      tags: [Greeting]
      operationId: app.api.get_greeting
      summary: Returns a custom greeting.
      responses:
        200:
          description: Return greeting
          schema:
            type: object
          examples:
            application/json:
                greeting: "Hello John"
      security:
        - basic: []
    post:
      tags: [Greeting]
      operationId: app.api.post_greeting
      summary: Returns a custom greeting.
      responses:
        200:
          description: Return greeting
          schema:
            type: object
          examples:
            application/json:
                greeting: "Hello John"
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              name:
                type: string
                example: "John"
            required:
              - name
      security:
        - basic: []
  /me:
    get:
      tags: [me]
      operationId: app.api.get_me
      summary: Return current user account details.
      responses:
        200:
          description: User Account Details
          schema:
            type: object
            properties:
              id:
                type: integer
                example: 1
              username:
                type: string
                example: "JohnDoe"
      security:
        - basic: []
    post:
      tags: [me]
      operationId: app.api.post_me
      summary: Create new user account
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              username:
                type: string
                format: username
              password:
                type: string
                format: secure_password
              email:
                type: string
                format: email
      responses:
        201:
          description: New user created
          schema:
            type: object
            properties:
              id:
                type: integer
              username:
                type: string
  "/me/password":
    put:
      tags: [me]
      operationId: app.api.put_me_password
      summary: Update user password
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              password:
                type: string
                format: secure_password
      responses:
        200:
          description: Password updated
  "/me/info":
    put:
      tags: [me]
      operationId: app.api.put_me_info
      summary: Update user information
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              username:
                type: string
      responses:
        200:
          description: User information updated
  "/me/token":
    get:
      tags: [me]
      operationId: app.api.get_me_token
      summary: Generate JSON Web Token
      responses:
        201:
          description: New token Created
          schema:
            type: object
            properties:
              token:
                type: string
      security:
        - basic: []
  /communityresource/register:
    post:
      tags: [communityresource]
      operationId: app.api.post_communityresource_register
      summary: Create a new community resource
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              number:
                type: string
              name:
                type: string
              address:
                type: string
              contact_name:
                type: string
              email:
                type: string
                format: email
              phone_number:
                type: string
      responses:
        200:
          description: New community resource created
          schema:
            type: object
            properties:
              id:
                type: integer
              number:
                type: integer
              name:
                type: string
              lat:
                type: number
              lon:
                type: number
              contact_name:
                type: string
              email:
                type: string
              phone_number:
                type: string
              verified:
                type: boolean
      security:
        - basic: []
  /communityresource/edit:
    put:
      tags: [communityresource]
      operationId: app.api.put_communityresource_edit
      summary: Edit an existing community resource
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              number:
                type: string
              email:
                type: string
                format: email
              phone_number:
                type: string
              name:
                type: string
              contact_name:
                type: string
              address:
                type: string
      responses:
        200:
          description: Community resource edited
          schema:
            type: object
            properties:
              number:
                type: integer
              name:
                type: string
              lat:
                type: number
              lon:
                type: number
              contact_name:
                type: string
              email:
                type: string
              phone_number:
                type: string
              verified:
                type: boolean
      security:
        - basic: []

securityDefinitions:
  basic:
    type: basic
